import type { ItineraryResponse } from "./types";

export const mockItinerary: ItineraryResponse = {
  destination: "Lisbon, Portugal",
  days: 5,
  nights: 4,
  budgetPerDay: 280,
  currency: "EUR",
  dayPlans: [
    {
      dayNumber: 1,
      theme: "Alfama & Fado",
      stay: "Memmo Alfama — heritage boutique with a panoramic Tagus terrace",
      morning: "Arrival and private transfer from the airport; settle in, then a slow espresso at a hillside miradouro.",
      afternoon: "Wander the Alfama's narrow lanes down to Sé de Lisboa cathedral, pausing at sunset-facing terraces.",
      evening: "Intimate Fado dinner in a small Alfama tasca — reserve a table by the stage in advance.",
      eveningBookInAdvance: true,
      eat: "Lunch at Taberna Sal Grosso; dinner at Casa de Linhares.",
      transitNotes: "Gentle walking through Alfama; take Tram 28 before 10:30 to avoid the midday queue.",
      estimatedCost: 230,
      budgetStatus: "under",
    },
    {
      dayNumber: 2,
      theme: "Chiado & Bairro Alto",
      stay: "Memmo Alfama (same stay)",
      morning: "Coffee and pastel de nata at a Chiado café, then browse the independent bookshops.",
      afternoon: "Elevador da Bica and a slow loop through Bairro Alto's murals and viewpoints.",
      evening: "Dinner reservation at Prado, a relaxed farm-to-table spot popular with locals.",
      eveningBookInAdvance: true,
      eat: "Lunch at a Time Out Market stall; dinner at Prado.",
      transitNotes: "Everything within an easy 20-minute walk; no transit needed.",
      estimatedCost: 310,
      budgetStatus: "over",
    },
    {
      dayNumber: 3,
      theme: "Belém & Jerónimos",
      stay: "Memmo Alfama (same stay)",
      morning: "Timed-entry visit to Jerónimos Monastery, then the riverside path toward the Belém Tower.",
      afternoon: "Pastéis de Belém for a snack, then a quiet afternoon at the MAAT waterfront museum.",
      evening: "Low-key dinner near the water, early night before the Sintra day trip.",
      eveningBookInAdvance: false,
      eat: "Lunch near Belém's riverside gardens; casual dinner back in Alfama.",
      transitNotes: "Tram 15 to Belém (roughly 25 minutes); avoid midday heat on the walk back.",
      estimatedCost: 205,
      budgetStatus: "under",
    },
    {
      dayNumber: 4,
      theme: "Sintra Day Trip",
      stay: "Memmo Alfama (same stay)",
      morning: "Early train to Sintra; Pena Palace grounds before the tour buses arrive.",
      afternoon: "Quinta da Regaleira's gardens and initiation well, then a slow lunch in the old town.",
      evening: "Return to Lisbon; light dinner, early rest.",
      eveningBookInAdvance: false,
      eat: "Lunch in Sintra's old town; simple dinner back in Lisbon.",
      transitNotes: "CP train from Rossio Station (~40 min); pre-book Pena Palace tickets for a morning slot.",
      estimatedCost: 260,
      budgetStatus: "on-target",
    },
    {
      dayNumber: 5,
      theme: "Slow Morning & Departure",
      stay: "Check-out",
      morning: "Unhurried breakfast on the terrace, a last walk through Alfama.",
      afternoon: "Final souvenir stop and private transfer to the airport.",
      evening: "Departure.",
      eveningBookInAdvance: false,
      eat: "Breakfast at the hotel; light lunch near the airport transfer.",
      transitNotes: "Private transfer booked the evening before.",
      estimatedCost: 120,
      budgetStatus: "under",
    },
  ],
  bookingChecklist: [
    { label: "Jerónimos Monastery fast-track tickets", dayNumber: 3, timeSlot: "09:30" },
    { label: "Casa de Linhares Fado dinner table", dayNumber: 1, timeSlot: "20:30" },
    { label: "Prado dinner reservation", dayNumber: 2, timeSlot: "20:45" },
    { label: "Private airport transfer (arrival)", dayNumber: 1 },
    { label: "Pena Palace morning entry slot", dayNumber: 4, timeSlot: "08:30" },
  ],
  curatorNote:
    "This draft balances relaxed mornings with a few booked prime-time reservations. Day 2 runs slightly over budget from the Prado dinner — worth flagging to the client or swapping for a lower-cost alternative if the budget is firm.",
};
